FROM arm32v7/alpine:3 AS binary
RUN apk add go
ADD . /app
WORKDIR /app
RUN env GOARCH=arm GOARM=7 GOOS=linux go build -o http

FROM arm32v7/alpine:3
WORKDIR /app
EXPOSE 8080
COPY --from=binary /app/http /app
CMD ["/app/http"]
