#!/bin/bash

# https://www.trion.de/news/2019/10/14/docker-multi-arch-dockerhub.html
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
chmod +x manifest-tool

./manifest-tool push from-spec multi-arch-manifest.yaml